### ISSUE TITLE
IP address raft endpoint

### ISSUE THREAD

**Issue by asad-awadia** [MicroRaft/MicroRaft#8]
Hey love the work done here. Was really looking for a nicer raft impl for JVM!

I am trying to understand how this would work with multiple machine IPs - in the atomic register example it doesn't use IPs

Where do the IPs go? Are they supposed to have ports as well? Any guides around how to connect multiple machines on a network?

**Comment by asad-awadia** [comment]
@metanet

**Comment by asad-awadia** [comment]
Tried a bunch of things but it can't elect a leader

**Comment by metanet** [comment]
@asad-awadia 

Thanks for evaluating MicroRaft!

The impl doesn't need to know ip addresses. It is abstracted away via [RaftEndpoint](https://github.com/MicroRaft/MicroRaft/blob/master/microraft/src/main/java/io/microraft/RaftEndpoint.java). You can write your own RaftEndpoint impl class which internally keeps ip addresses for your nodes, and implement the networking via [Transport](https://github.com/MicroRaft/MicroRaft/blob/master/microraft/src/main/java/io/microraft/transport/Transport.java). 

You can check https://microraft.io/docs/main-abstractions/ and Javadocs for more info. I will add an example project which uses gRPC for comm. soon.

Cheers,

**Comment by asad-awadia** [comment]
@metanet yeah that is what I did but that doesn't mean anything as it is just an "id" - 

```
class MyRaftEndpoint(private val ip: String) : RaftEndpoint {
  override fun getId(): Any {
    return ip
  }
}
```

The transport also has no return value on the send message - what does it need to do? how does the other side receive the message and use it in microraft?? I can send it over http but what is the request handler supposed to do with it?

**Comment by metanet** [comment]
For the Raft code, it is enough to identify each node and send messages to them. You can make use of ip addresses inside your real `Transport` implementation. 

Each message is basically fire & forget, that is why `Transport.send()` is a void method. If a Transport impl fails to deliver a message to the target Raft node, it is fine, and MicroRaft will retry the same message after some time. Since it works with fire & forget, if you are writing an HTTP transport, each RaftNode can run its own HTTP server and behave as HTTP clients for each other. When your HTTP server receives a `RaftMessage` object, it can pass the object to `RaftNode.handle()` and return an OK response. Then, this `RaftNode` will execute this message and make another HTTP call back to the original caller via the same logic.

**Comment by asad-awadia** [comment]
ok I get it

Trying to do that but the RaftMessage object is a pain to send over the wire - just interfaces upon interfaces upon factories.. how do you even tell which kind of request is it?

is there a simple way to convert it to json or bytes?
